name: Tests
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v4.3.0
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type Check
        run: pnpm ts

      - name: Build
        run: pnpm build
